name: tajer
description: "Tajer - Merchant Inventory and Order Management System"
publish_to: 'none'
version: 1.0.133+133

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  wakelock_plus: ^1.2.8

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_analytics: ^11.0.0
  google_sign_in: ^6.2.1

  # Security & Anti-Tamper
  ntp: ^2.0.0

  url_launcher: ^6.2.2
  shared_preferences: ^2.2.3
  uuid: ^4.3.3
  purchases_flutter: ^10.6.0
  device_info_plus: ^10.1.0
  flutter_staggered_grid_view: ^0.6.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^14.0.0

  # Code Generation Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Scanner
  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1

  # Charts and Reports
  fl_chart: ^0.68.0

  # PDF Generation and Printing
  image: ^4.1.7
  pdf: ^3.11.0
  printing: ^5.12.0
  print_bluetooth_thermal: ^1.2.1
  esc_pos_utils_plus: ^2.0.3
  excel: ^4.0.3

  # Backup & Storage
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  firebase_storage: ^12.0.0
  workmanager: ^0.10.7
  firebase_ui_firestore: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  custom_lint: ^0.6.2
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

  integration_test:
    sdk: flutter
  fake_cloud_firestore: ^3.0.2
  mockito: ^5.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
    - assets/fonts/

dependency_overrides:
  package_info_plus: ^8.0.0
