import json

arb_path = 'lib/l10n/app_ar.arb'

# We will load it, fix known keys, and save it.
with open(arb_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# The correct Arabic translations:
fixes = {
  "accountingReport": "تقرير دفتر المحاسبة",
  "genericErrorPrefix": "خطأ",
  "notebookCategories": "التصنيفات",
  "notebookTransactions": "الحركات",
  "notebookNoData": "لا توجد بيانات.",
  "notebookAddBook": "إضافة دفتر",
  "notebookBookName": "اسم الدفتر",
  "notebookEditBook": "تعديل الدفتر",
  "notebookArchiveBook": "أرشفة الدفتر",
  "notebookArchiveConfirm": "هل أنت متأكد من الأرشفة؟",
  "archive": "أرشفة",
  "notebookAddCategory": "إضافة تصنيف",
  "notebookCategoryName": "اسم التصنيف",
  "notebookEditCategory": "تعديل التصنيف",
  "notebookArchiveCategory": "أرشفة التصنيف",
  "notebookAddAccount": "إضافة حساب",
  "notebookEditAccount": "تعديل حساب",
  "notebookArchiveAccount": "أرشفة حساب",
  "notebookAccountName": "اسم الحساب",
  "notebookAccountType": "نوع الحساب",
  "notebookOpeningBalance": "الرصيد الافتتاحي",
  "notebookAddPerson": "إضافة شخص",
  "notebookEditPerson": "تعديل شخص",
  "notebookArchivePerson": "أرشفة شخص",
  "notebookPersonName": "اسم الشخص",
  "notebookPersonPhone": "رقم الهاتف",
  "notebookNote": "ملاحظة",
  "notebookTransfer": "تحويل",
  "notebookSourceAccount": "حساب المصدر",
  "notebookDestinationAccount": "حساب الوجهة",
  "notebookPayment": "سداد",
  "notebookPartialPayment": "سداد جزئي",
  "notebookFullPayment": "سداد كامل",
  "notebookStatement": "كشف حساب",
  "notebookFilters": "تصفية",
  "notebookTotalOwedToMe": "إجمالي لي",
  "notebookTotalIOwe": "إجمالي عليّ",
  "notebookNetBalance": "صافي الرصيد",
  "notebookTypeCash": "نقدي",
  "notebookTypeBank": "بنك",
  "notebookTypeCard": "بطاقة",
  "notebookTypeWallet": "محفظة إلكترونية",
  "notebookTypeOther": "أخرى",
  "notebookDateRange": "نطاق التاريخ",
  "notebookTransactionType": "نوع الحركة",
  "notebookPaymentOfDebt": "سداد دين",
  "notebookCreateBookFirst": "يرجى إنشاء دفتر أولاً.",
  "notebookCreateCategoryFirst": "يرجى إنشاء تصنيف أولاً.",
  "notebookAll": "الكل",
  "notebookStartDate": "تاريخ البداية",
  "notebookEndDate": "تاريخ النهاية",
  "notebookApplyFilters": "تطبيق التصفية",
  "notebookClearFilters": "مسح التصفية",
  "notebookRequired": "مطلوب",
  "notebookInvalidAmount": "مبلغ غير صحيح",
  "notebookAmountExceedsDebt": "المبلغ يتجاوز قيمة الدين",
  "notebookSourceDestSame": "لا يمكن أن يكون المصدر والوجهة متطابقين",
  "notebookCreateAccountFirst": "الرجاء إنشاء حساب أولاً",
  "notebookCreatePersonFirst": "الرجاء إنشاء شخص أولاً",
  "notebookPerson": "الشخص",
  "notebookAccount": "الحساب",
  "notebookBook": "الدفتر",
  "notebookCategory": "التصنيف",
  "notebookAmount": "المبلغ",
  "notebookCancel": "إلغاء",
  "notebookSave": "حفظ",
  "notebookArchive": "أرشفة",
  "notebookEdit": "تعديل",
  "notebookDelete": "حذف",
  "notebookPayable": "عليّ",
  "notebookReceivable": "لي",
  "notebookToday": "اليوم",
  "notebookWeek": "هذا الأسبوع",
  "notebookMonth": "هذا الشهر",
  "notebookNetIncome": "صافي الدخل",
  "notebookDebtAndAccounts": "الديون والحسابات",
  "permCanAccessAccountingNotebook": "دفتر المحاسبة",
  "permCanAccessAccountingNotebookDesc": "السماح للموظف بالدخول إلى دفتر المحاسبة وإدارة بياناته",
  "notebookBalance": "الرصيد",
  "notebookEmptyBooks": "ابدأ بإنشاء دفتر لتنظيم حسابات نشاطك.",
  "notebookEmptyAccounts": "يرجى إنشاء حساب مالي أولاً لتسجيل العمليات.",
  "notebookEmptyPeople": "أضف شخصًا أولاً (عميل أو مورد) لتسجيل المبالغ.",
  "notebookCreateBookCTA": "إنشاء دفتر",
  "notebookCreateAccountCTA": "إنشاء حساب مالي",
  "notebookAddPersonCTA": "إضافة شخص",
  "notebookIncomeHint": "سجل هنا الأموال التي دخلت إلى أحد حساباتك. (مثال: مبيعات نقدية، دخل إضافي، إيداع)",
  "notebookExpenseHint": "سجل هنا الأموال التي خرجت من أحد حساباتك. (مثال: إيجار، مشتريات، صيانة)",
  "notebookReceivableHint": "استخدم (لي) عندما يكون لك مبلغ عند عميل أو شخص آخر.",
  "notebookPayableHint": "استخدم (علي) عندما يكون عليك مبلغ لمورد أو شخص آخر.",
  "notebookFilterType": "نوع الحركة",
  "notebookFilterBook": "الدفتر",
  "notebookFilterAccount": "الحساب",
  "notebookReceivePayment": "استلام دفعة",
  "notebookPayPayment": "دفع مبلغ",
  "notebookOverpaymentError": "المبلغ المدخل أكبر من الرصيد المتبقي",
  "notebookSameAccountError": "لا يمكن التحويل لنفس الحساب",
  "notebookPartialPaymentHint": "المبلغ المراد سداده",
  "notebookAccountsCreateFirst": "الرجاء إنشاء حساب مالي أولاً",
  "notebookNoAccountsFound": "لا توجد حسابات",
  "notebookNoPeopleFound": "لا يوجد أشخاص",
  "notebookNoCategoriesFound": "لا توجد تصنيفات",
  "notebookNoTransactionsYet": "لا توجد حركات بعد",
  "notebookTitle": "دفتر المحاسبة",
  "notebookBooks": "الدفاتر",
  "notebookAccounts": "الحسابات المالية",
  "notebookPeople": "الأشخاص",
  "notebookIncome": "دخل",
  "notebookExpense": "مصروف"
}

# Update any key that starts with notebook, or specific ones.
for k, v in data.items():
    if k in fixes:
        data[k] = fixes[k]

with open(arb_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
