name: Build Android App Bundle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'any'
        channel: 'stable'

    - name: Decode Keystore
      run: |
        echo "Keystore is already in repository as tajer-release.jks"

    - name: Install dependencies
      run: flutter pub get

    - name: Run build_runner
      run: dart run build_runner build -d

    - name: Build Android App Bundle
      run: flutter build appbundle --release 

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/bundle/release/app-release.aab
