name: Build Tajer App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Adjust to latest stable
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --release --web-renderer canvaskit --base-href /taj/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tajer-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: tajer-web
          path: build/web
